apply plugin: 'com.android.application'

android {
    compileSdk {
        version = release(37)
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlin {
        jvmToolchain(17)
    }
    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    defaultConfig {
        applicationId = "pl.pzienowicz.zditmszczecinlive"
        minSdk {
            version = release(23)
        }
        targetSdk {
            version = release(36)
        }
        versionCode = 71
        versionName = "1.20.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace = 'pl.pzienowicz.zditmszczecinlive'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'

    implementation 'com.android.billingclient:billing:9.1.0'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'com.karumi:dexter:6.2.3'
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'

    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'com.google.android.gms:play-services-location:21.4.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    implementation 'com.squareup.okhttp3:logging-interceptor:5.4.0'

    implementation 'org.jsoup:jsoup:1.22.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
}
